# Generated by Django 2.0.5 on 2018-05-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180528_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Parody')], default='M', max_length=1, null=True),
        ),
    ]
