# Generated by Django 2.0.5 on 2018-05-29 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myblog', '0003_delete_pengumuman'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(default='unknown', max_length=50, null=True)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='untitled', max_length=200, null=True)),
                ('content', models.TextField(default='blank content', null=True)),
            ],
        ),
    ]
